// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package chunkify

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"
	"time"

	"github.com/chunkifydev/chunkify-go/internal/apijson"
	"github.com/chunkifydev/chunkify-go/internal/requestconfig"
	"github.com/chunkifydev/chunkify-go/option"
	"github.com/chunkifydev/chunkify-go/packages/respjson"
	"github.com/chunkifydev/chunkify-go/shared"
	"github.com/chunkifydev/chunkify-go/shared/constant"
)

// JobTranscoderService contains methods and other services that help with
// interacting with the chunkify API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewJobTranscoderService] method instead.
type JobTranscoderService struct {
	Options []option.RequestOption
}

// NewJobTranscoderService generates a new service that applies the given options
// to each request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewJobTranscoderService(opts ...option.RequestOption) (r JobTranscoderService) {
	r = JobTranscoderService{}
	r.Options = opts
	return
}

// Retrieve all the transcoders statuses for a specific job
func (r *JobTranscoderService) List(ctx context.Context, jobID string, opts ...option.RequestOption) (res *JobTranscoderListResponse, err error) {
	var preClientOpts = []option.RequestOption{requestconfig.WithProjectAccessTokenSecurity()}
	opts = slices.Concat(preClientOpts, r.Options, opts)
	if jobID == "" {
		err = errors.New("missing required jobId parameter")
		return nil, err
	}
	path := fmt.Sprintf("api/jobs/%s/transcoders", jobID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Response containing a list of transcoders for a job
type JobTranscoderListResponse struct {
	Data []JobTranscoderListResponseData `json:"data" api:"required"`
	// Status indicates the response status "success"
	Status constant.Success `json:"status" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Data        respjson.Field
		Status      respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r JobTranscoderListResponse) RawJSON() string { return r.JSON.raw }
func (r *JobTranscoderListResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type JobTranscoderListResponseData struct {
	// Unique identifier of the transcoder
	ID string `json:"id" api:"required"`
	// Billable time in seconds
	BillableTime int64 `json:"billable_time" api:"required"`
	// End time of the current chunk in seconds
	ChunkEndTime float64 `json:"chunk_end_time" api:"required"`
	// Number of the chunk being processed
	ChunkNumber int64 `json:"chunk_number" api:"required"`
	// Start time of the current chunk in seconds
	ChunkStartTime float64 `json:"chunk_start_time" api:"required"`
	// CPU time used for transcoding in seconds
	CPUTime float64 `json:"cpu_time" api:"required"`
	// Timestamp when the status was created
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Current frames per second being processed
	Fps float64 `json:"fps" api:"required"`
	// Current frame number being processed
	Frame int64 `json:"frame" api:"required"`
	// Unique identifier of the job
	JobID string `json:"job_id" api:"required"`
	// Current output time in seconds
	OutTime int64 `json:"out_time" api:"required"`
	// Progress percentage of the transcoding operation (0-100)
	Progress float64 `json:"progress" api:"required"`
	// Current processing speed multiplier
	Speed float64 `json:"speed" api:"required"`
	// Current status of the transcoder (starting, transcoding, finished, failed)
	//
	// Any of "starting", "pending", "transcoding", "completed", "failed", "cancelled".
	Status string `json:"status" api:"required"`
	// Unique identifier of the transcoder instance (generated by the transcoder)
	TranscoderInstanceID string `json:"transcoder_instance_id" api:"required"`
	// Timestamp when the status was last updated
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Error message if the transcoding failed
	Error shared.ChunkifyError `json:"error"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ID                   respjson.Field
		BillableTime         respjson.Field
		ChunkEndTime         respjson.Field
		ChunkNumber          respjson.Field
		ChunkStartTime       respjson.Field
		CPUTime              respjson.Field
		CreatedAt            respjson.Field
		Fps                  respjson.Field
		Frame                respjson.Field
		JobID                respjson.Field
		OutTime              respjson.Field
		Progress             respjson.Field
		Speed                respjson.Field
		Status               respjson.Field
		TranscoderInstanceID respjson.Field
		UpdatedAt            respjson.Field
		Error                respjson.Field
		ExtraFields          map[string]respjson.Field
		raw                  string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r JobTranscoderListResponseData) RawJSON() string { return r.JSON.raw }
func (r *JobTranscoderListResponseData) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
